### ISSUE TITLE
Shaperglot report stops after 'ace_Latn' (Achinese)

### ISSUE THREAD

**Issue by laepage** [googlefonts/shaperglot#34]
Hello, tried to test a font's coverage, and the script stopped after 7 languages with an error
**"TypeError: 'NoneType' object is not iterable"**

(Tried with a Python 3.12.0 virtualenv, but the error remains the same)

shaperglot report ***-Roman.ttf                                                    

Font supports language 'aa_Latn' (Afar)
Font does not fully support language 'ab_Cyrl' (Abkhazian)
Font does not fully support language 'abi_Latn' (Abidji)
Font does not fully support language 'abn_Latn' (Abua)
Font does not fully support language 'abq_Cyrl' (Abaza)
Font does not fully support language 'abr_Latn' (Abron)
Font does not fully support language 'acd_Latn' (Gikyode)
Font supports language 'ace_Latn' (Achinese)

Traceback (most recent call last):
  File "/.pyenv/versions/shaperglot_py3-9/bin/shaperglot", line 8, in <module>
    sys.exit(main())
  File "/.pyenv/versions/3.9.18/envs/shaperglot_py3-9/lib/python3.9/site-packages/shaperglot/cli.py", line 189, in main
    options.func(options)
  File "/.pyenv/versions/3.9.18/envs/shaperglot_py3-9/lib/python3.9/site-packages/shaperglot/cli.py", line 75, in report
    results = checker.check(langs[lang])
  File "/.pyenv/versions/3.9.18/envs/shaperglot_py3-9/lib/python3.9/site-packages/shaperglot/checker.py", line 62, in check
    check_object.execute(self)
  File "/.pyenv/versions/3.9.18/envs/shaperglot_py3-9/lib/python3.9/site-packages/shaperglot/checks/no_orphaned_marks.py", line 35, in execute
    zip(buffer.glyph_infos, buffer.glyph_positions)

TypeError: 'NoneType' object is not iterable

**Comment by simoncozens** [comment]
I think this is fixed in git but I need to make a release

**Comment by simoncozens** [comment]
Fixed in v0.3.1

**Comment by laepage** [comment]
Thanks, thanks, it's working now!
